[chore] 폴더명 변경
boostcampwm-2024/and01-dreamDiary pull request #109
Opened 2024-11-12 10:12 UTC by easyhak

## :man_shrugging: Description
- 폴더명 복수에서 단수로 적용
- label 기본값

2024-11-12 10:14 UTC, ruh0n requested changes

2024-11-12 10:14 UTC, ruh0n commented on feature/diary/src/main/java/com/boostcamp/dreamteam/dreamdiary/feature/diary/home/components/DiaryCard.kt
components...

2024-11-12 10:42 UTC, flashdragon approved these changes
굳

2024-11-13 00:34 UTC, ruh0n requested changes
[수정 요청]  
feature/diary/home/components

[확인 필요]
core/data/schemas

2024-11-13 02:09 UTC, ruh0n reviewed
LGTM

2024-11-13 02:11 UTC, minwooch approved these changes

2024-11-13 02:12 UTC, ruh0n approved these changes

2024-11-13 02:14 UTC, merged