[feat] 나의 일기 목록(리스트) 화면 구현
boostcampwm-2024/and01-dreamDiary pull request #35
Opened 2024-11-04 10:43 UTC by ruh0n

- close: #10, #11 

- [feat] 나의 일기 목록(리스트) 화면 구현
## :memo: Primary Commits

## :camera: Screenshots

2024-11-04 10:51 UTC, minwooch requested changes

2024-11-04 10:51 UTC, minwooch commented on feature/diary/src/main/java/com/boostcamp/dreamteam/dreamdiary/feature/diary/components/DiaryCard.kt
> +                    model = diary.images.firstOrNull(),
여기 이 부분 it로 하시면 될 것 같습니다.

2024-11-04 10:52 UTC, ruh0n commented on feature/diary/src/main/java/com/boostcamp/dreamteam/dreamdiary/feature/diary/components/DiaryCard.kt
> +                    model = diary.images.firstOrNull(),
```suggestion
            diary.images.firstOrNull()?.let {
                AsyncImage(
                    model = it,
```

2024-11-04 10:56 UTC, ruh0n commented on feature/diary/src/main/java/com/boostcamp/dreamteam/dreamdiary/feature/diary/components/DiaryCard.kt
> +                    model = diary.images.firstOrNull(),
스코프 블럭으로 이전하는 과정에서 실수가 있던 것 같습니다.

아래의 comment의 suggestion을 통해 해결 했습니다.

2024-11-04 14:55 UTC, easyhak approved these changes
수고하셨습니다

2024-11-05 01:28 UTC, minwooch approved these changes
굿

2024-11-05 01:28 UTC, merged