Feature/label selection UI
boostcampwm-2024/and01-dreamDiary pull request #66
Opened 2024-11-06 11:31 UTC by easyhak

close #51

## :man_shrugging: Description
- 라벨 아이콘 클릭시 카테고리 선택할 수 있는 다이이얼로그 나오도록 구현

## :camera: Screenshots

![image](https://github.com/user-attachments/assets/d8fed466-7bbd-4d53-959f-f1b482bf8362)

## 기타
- ui는 사람들 피드백 받고서 수정여부 결정

2024-11-06 11:37 UTC, easyhak commented on feature/diary/src/main/java/com/boostcamp/dreamteam/dreamdiary/feature/diary/write/DiaryWriteScreen.kt
> +                    IconButton(onClick = { /*TODO*/ }) {
수정했습니다

2024-11-06 12:44 UTC, ruh0n requested changes

2024-11-06 12:44 UTC, ruh0n commented on feature/diary/src/main/java/com/boostcamp/dreamteam/dreamdiary/feature/diary/write/DiaryWriteScreen.kt
> +                labelList = listOf("악몽", "개꿈", "귀신"),
재우님 설명 들으면서 든 생각입니다.
이런 테스트(프리뷰)용 임시 코드가 dev에 포함되어도 될 지 궁금합니다.

2024-11-06 12:44 UTC, ruh0n commented on feature/diary/src/main/java/com/boostcamp/dreamteam/dreamdiary/feature/diary/write/components/LabelItem.kt
> +    modifier: Modifier = Modifier,
modifier는 기본값이 있는 파라미터 중 처음에 오는 것이 좋을 것 같습니다.

2024-11-06 12:44 UTC, ruh0n commented on feature/diary/src/main/java/com/boostcamp/dreamteam/dreamdiary/feature/diary/write/components/LabelItem.kt
> +            modifier = Modifier,
없어도 되는 라인인 것 같습니다.

2024-11-06 12:44 UTC, ruh0n commented on feature/diary/src/main/java/com/boostcamp/dreamteam/dreamdiary/feature/diary/write/components/LabelItem.kt
> +fun LabelItemPreview() {
프리뷰는 private인 것이 더 좋을 것 같습니다.

대부분의 경우 프리뷰를 theme으로 감싸는데 감싸지 않은 이유도 궁금합니다.

2024-11-06 12:44 UTC, ruh0n commented on feature/diary/src/main/java/com/boostcamp/dreamteam/dreamdiary/feature/diary/write/components/LabelSelectionDialog.kt
> +fun LabelSelectionDialog(
다른 곳에서는 internal키워드를 사용했는데
여기에는 사용하지 않으신 이유가 궁금합니다.

2024-11-06 12:44 UTC, ruh0n commented on feature/diary/src/main/java/com/boostcamp/dreamteam/dreamdiary/feature/diary/write/components/LabelSelectionDialog.kt
> +    searchValueChange: (String) -> Unit,
다른 람다는 on을 사용하셨는데  
이친구는 onSearchValueChange가 아닌 이유가 궁금합니다.

2024-11-06 12:44 UTC, ruh0n commented on feature/diary/src/main/java/com/boostcamp/dreamteam/dreamdiary/feature/diary/write/components/LabelSelectionDialog.kt
> +                .fillMaxWidth(),
외부에서 받아 온 modifier는 최상단의 compose에 사용하는 것이 맞는 것으로 알고 있는데

내부의 surface에서 사용하신 이유가 궁금합니다.

2024-11-06 12:44 UTC, ruh0n commented on feature/diary/src/main/java/com/boostcamp/dreamteam/dreamdiary/feature/diary/write/components/LabelSelectionDialog.kt
> +fun LabelSelectionDialogPreview() {
프리뷰는 private인 것이 더 좋을 것 같습니다.

대부분의 경우 프리뷰를 theme으로 감싸는데 감싸지 않은 이유도 궁금합니다. 2

2024-11-06 12:44 UTC, ruh0n commented on feature/diary/src/main/java/com/boostcamp/dreamteam/dreamdiary/feature/diary/write/components/LabelItem.kt
> +    onCheckChanged: (Boolean) -> Unit,
`onCheckChanged`   
d가 있는 이유가 궁금합니다.

2024-11-06 12:44 UTC, ruh0n commented on feature/diary/src/main/java/com/boostcamp/dreamteam/dreamdiary/feature/diary/write/DiaryWriteViewModel.kt
> +    fun setLabels(labels: List<String>) {
리스트를 바로 set 한다는 것에 조금 위화감이 드는 것 같습니다.

문제가 없을 지 다른 분들의 의견도 궁금합니다.

2024-11-06 12:44 UTC, ruh0n commented on feature/diary/src/main/java/com/boostcamp/dreamteam/dreamdiary/feature/diary/write/model/DiaryWriteUiState.kt
> +    val labels: List<String> = emptyList(),
`LabelUi`라는 ui model이 존재해서 변경해주시는 것이 좋을 것 같습니다.

2024-11-06 12:44 UTC, ruh0n commented on feature/diary/src/main/java/com/boostcamp/dreamteam/dreamdiary/feature/diary/write/model/DiaryWriteUiState.kt
> +    val selectedLabels: List<Boolean> = emptyList(),
단순 의견이 궁금해서 남기는 질문입니다.

래퍼클래스를 만들어서 관리하는 것은 어떨까요?

ex)
```kotlin
data class SelectableLabel(
	val value: LabelUi,
    val isSelected: Boolean
)

2024-11-06 13:59 UTC, easyhak commented on feature/diary/src/main/java/com/boostcamp/dreamteam/dreamdiary/feature/diary/write/components/LabelItem.kt
> +fun LabelItemPreview() {
theme으로 감싸지 않은 이유는 아무생각이 없었습니다...

2024-11-06 14:05 UTC, easyhak commented on feature/diary/src/main/java/com/boostcamp/dreamteam/dreamdiary/feature/diary/write/components/LabelItem.kt
> +    onCheckChanged: (Boolean) -> Unit,
.net 같은 것에만 d가 들어가네요... 네이밍 다 수정하겠습니다

2024-11-06 14:10 UTC, easyhak commented on feature/diary/src/main/java/com/boostcamp/dreamteam/dreamdiary/feature/diary/write/components/LabelSelectionDialog.kt
> +fun LabelSelectionDialog(
사용하겠습니다. 습관이 덜 들었네요

2024-11-06 14:11 UTC, easyhak commented on feature/diary/src/main/java/com/boostcamp/dreamteam/dreamdiary/feature/diary/write/components/LabelItem.kt
> +    modifier: Modifier = Modifier,
헐 이런 컨벤션도 있네요

2024-11-06 14:11 UTC, easyhak commented on feature/diary/src/main/java/com/boostcamp/dreamteam/dreamdiary/feature/diary/write/components/LabelSelectionDialog.kt
> +    searchValueChange: (String) -> Unit,
저도 onSearchValueChange가 더 마음에 드네요

2024-11-06 14:12 UTC, easyhak commented on feature/diary/src/main/java/com/boostcamp/dreamteam/dreamdiary/feature/diary/write/components/LabelSelectionDialog.kt
> +                .fillMaxWidth(),
alertDialog를 사용하다가 기본 padding 값이 있어서 그냥 Dialog로 변경하다가 실수했습니다

2024-11-06 14:15 UTC, easyhak commented on feature/diary/src/main/java/com/boostcamp/dreamteam/dreamdiary/feature/diary/write/components/LabelSelectionDialog.kt
> +                .fillMaxWidth(),
AlertDialog에서 Dialog로 변경할 때 발생한 실수인줄알았는데 Dialog의 parameter로는 modifier가 없습니다.

2024-11-06 14:23 UTC, easyhak commented on feature/diary/src/main/java/com/boostcamp/dreamteam/dreamdiary/feature/diary/write/DiaryWriteScreen.kt
> +                labelList = listOf("악몽", "개꿈", "귀신"),
지금은 실제로 release한 것도 아니고 개발 초기 단계이기에 저는 상관없다고 생각합니다.

오히려 이 코드가 없다면 이것이 무엇을 의미하는지 더 어려워질 수 있다고 생각합니다. 또한 preview를 없앤다면 위에 날짜, 시간 등을 다 지워야하는데 그러면 개발속도를 늦추기만 할 것이라고 생각합니다.

main(release) branch에만 이러한 코드가 들어가지만 않으면 괜찮을 것 같습니다.

제 생각이니 다른 분들 의견 받고 어떻게 할지 정해보죠!!!👍

2024-11-06 14:27 UTC, easyhak commented on feature/diary/src/main/java/com/boostcamp/dreamteam/dreamdiary/feature/diary/write/model/DiaryWriteUiState.kt
> +    val selectedLabels: List<Boolean> = emptyList(),
저도 이러한 방식이 더 마음에 들어서 이렇게 수정하려다가 UI 수정한다는 마음에 꺾이긴 했었던 부분입니다. 이번주 금요일날 UI쪽 리뷰한번 받아보고 진행할까요?? 아니면 오늘 태준님이 말씀해주신대로 UI를 새로 수정해볼까요?

2024-11-06 14:42 UTC, easyhak commented on feature/diary/src/main/java/com/boostcamp/dreamteam/dreamdiary/feature/diary/write/model/DiaryWriteUiState.kt
> +    val labels: List<String> = emptyList(),
여기서 폴더명이 model인데 models로 통일을 할까요? 아니면 model로 할까요?

2024-11-06 14:45 UTC, easyhak commented on feature/diary/src/main/java/com/boostcamp/dreamteam/dreamdiary/feature/diary/write/model/DiaryWriteUiState.kt
> +    val labels: List<String> = emptyList(),
https://softwareengineering.stackexchange.com/questions/75919/should-package-names-be-singular-or-plural

이런 글이 있네요

2024-11-06 23:34 UTC, ruh0n commented on feature/diary/src/main/java/com/boostcamp/dreamteam/dreamdiary/feature/diary/write/components/LabelSelectionDialog.kt
> +                .fillMaxWidth(),
@easyhak 헐 이건 저도 몰랐네요

2024-11-06 23:47 UTC, ruh0n commented on feature/diary/src/main/java/com/boostcamp/dreamteam/dreamdiary/feature/diary/write/model/DiaryWriteUiState.kt
> +    val labels: List<String> = emptyList(),
해당 글은 저랑 같은 의견인것 같은데요?

`plural for packages with homogeneous contents`  
`A package named com.myproject.tasks, however, would contain different types that are all tasks: TakeOutGarbageTask, DoTheDishesTask, etc.`

저희도 `ㅇㅇModel`, `ㅁㅁModel` 이 같은 패키지 안에 있으니 models가 맞다고 생각했던 것입니다.

이것도 한번 더 고민 해보죠

2024-11-07 03:18 UTC, minwooch approved these changes
굿

2024-11-07 06:35 UTC, flashdragon approved these changes
굳

2024-11-07 10:59 UTC, merged